version: "3.8"
services:
  api:
    build:
      context: ./chat-api
      dockerfile: dockerfile
    container_name: api
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      PORT: 3000

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: client
    depends_on:
      - api
    ports:
      - 4200:4200
    links:
      - api
