services:
  api:
    build:
      target: production
      args:
        - NODE_ENV=production
    environment:
      NODE_ENV: production

  client:
    build:
      target: production
      args:
        - NODE_ENV=production
    ports:
      - 80:80
      - 8080:8080
