services:
  api:
    build:
      target: development
      args:
        - NODE_ENV=development
    environment:
      NODE_ENV: development
    command: npm run start:dev
    volumes:
      - ./chat-api:/app
      - /app/node_modules

  client:
    build:
      target: development
      args:
        - NODE_ENV=development
    command: npm run start
    volumes:
      - ./client:/app
      - /app/node_modules
