FROM node:16-alpine as development

#Set up working DIR
WORKDIR /app

# Copy package-lock.json & package.json from host to inside container working directory
COPY package*.json .

# Install deps inside container
ARG NODE_ENV
RUN if [ "${NODE_ENV}" = "development" ]; \
        then npm install --also=dev; \
        else npm install --only=production; \
        fi

#  Bundle App Sources
COPY . .

EXPOSE 3001
CMD [ "npm", "start" ]


##################
## Test & Build ##
##################
FROM node:16-alpine as build

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app/build
COPY --from=development app/ .

RUN npm run build

################
## PRODUCTION ##
################
FROM node:16-alpine as production

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY --from=build app/build .


EXPOSE 3001

# run app
CMD [ "node", "dist/main"]